/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package marianorolong.Ventanas.Castings;

import java.util.Date;
import java.util.HashMap;
import javax.swing.JOptionPane;
import marianorolong.base.Casting;



/**
 *
 * @author maria
 */
public class VentanaCasting extends javax.swing.JDialog {
    Casting casting;
    /**
     * Creates new form VentanaUsuarios
     */
    public VentanaCasting(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        campoCodigoCasting = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        campoNombreCasting = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        campoDescripcionCasting = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        campoCosto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        campoFechaContratacion = new org.jdesktop.swingx.JXDatePicker();
        campoTipoDeCasting = new javax.swing.JTextField();
        campoNumeroDePersonas = new javax.swing.JTextField();
        botonGuardar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        botonBuscar = new javax.swing.JButton();
        botonEditar = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("..USER FORM");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("FORMULARIO PARA GESTIONAR CASTINGS");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0), 2), "DatosDelCasting", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 16), new java.awt.Color(255, 153, 0))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Codigo Casting:");

        campoCodigoCasting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCodigoCastingActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Contratación");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Nombre Casting:");

        campoNombreCasting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreCastingActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Descripcion:");

        campoDescripcionCasting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDescripcionCastingActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Costo:");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Tipo:");

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("# Personas:");

        campoFechaContratacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoFechaContratacionActionPerformed(evt);
            }
        });

        campoNumeroDePersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNumeroDePersonasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(campoFechaContratacion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(campoCodigoCasting, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(campoNumeroDePersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoTipoDeCasting, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 22, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(campoDescripcionCasting, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(campoCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoNombreCasting, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campoCodigoCasting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(campoTipoDeCasting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(campoFechaContratacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(campoNumeroDePersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(campoNombreCasting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(campoDescripcionCasting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(campoCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        botonGuardar.setBackground(new java.awt.Color(255, 153, 0));
        botonGuardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonGuardar.setForeground(new java.awt.Color(0, 0, 0));
        botonGuardar.setText("GUARDAR");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        botonCancelar.setBackground(new java.awt.Color(255, 153, 0));
        botonCancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonCancelar.setForeground(new java.awt.Color(0, 0, 0));
        botonCancelar.setText("CANCELAR");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marianorolong/Ventanas/iconos/castingFormularioIcono.png"))); // NOI18N

        botonBuscar.setBackground(new java.awt.Color(255, 153, 0));
        botonBuscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonBuscar.setForeground(new java.awt.Color(0, 0, 0));
        botonBuscar.setText("BUSCAR");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        botonEditar.setBackground(new java.awt.Color(255, 153, 0));
        botonEditar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonEditar.setForeground(new java.awt.Color(0, 0, 0));
        botonEditar.setText("EDITAR");
        botonEditar.setEnabled(false);
        botonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarActionPerformed(evt);
            }
        });

        botonEliminar.setBackground(new java.awt.Color(255, 153, 0));
        botonEliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonEliminar.setForeground(new java.awt.Color(0, 0, 0));
        botonEliminar.setText("ELIMINAR");
        botonEliminar.setEnabled(false);
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(botonEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botonEliminar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonCancelar)
                                .addGap(18, 18, 18)
                                .addComponent(botonBuscar)
                                .addGap(18, 18, 18)
                                .addComponent(botonGuardar)))
                        .addGap(140, 140, 140)))
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonCancelar)
                            .addComponent(botonBuscar)
                            .addComponent(botonGuardar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonEditar)
                            .addComponent(botonEliminar))))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoNombreCastingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreCastingActionPerformed
    
    }//GEN-LAST:event_campoNombreCastingActionPerformed
       public void limpiarCampos(){
        campoCodigoCasting.setText("");
        campoNumeroDePersonas.setText(""); 
        campoTipoDeCasting.setText("");
        campoNombreCasting.setText("");
        campoFechaContratacion.getEditor().setText("");
        campoFechaContratacion.getEditor().setEditable(false);
        campoDescripcionCasting.setText("");
        campoCosto.setText("");
           
        botonEditar.setEnabled(false);
        botonEliminar.setEnabled(false);
       }
    
    private void campoDescripcionCastingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDescripcionCastingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDescripcionCastingActionPerformed

    private void campoCodigoCastingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCodigoCastingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCodigoCastingActionPerformed

    private void campoFechaContratacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoFechaContratacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoFechaContratacionActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
    
        
    String codigoCasting = campoCodigoCasting.getText();
    Date fechaContratacion = campoFechaContratacion.getDate(); 
    String nombre = campoNombreCasting.getText();
    String descripcion = campoDescripcionCasting.getText();
    String costo = campoCosto.getText();
    String tipo = campoTipoDeCasting.getText();
    String numeroPersonasRequeridas = campoNumeroDePersonas.getText();

       
        
        
        //crear variable casting
       
        Casting a = new Casting();
    a.codigoCasting = codigoCasting;
    a.fechaContratacion=fechaContratacion;
    a.nombre=nombre;
    a.descripcion=descripcion;
    a.costo =costo;
    a.tipo =tipo;
    a.numeroPersonasRequeridas = numeroPersonasRequeridas;
        
        
       
        // VERIFICAR SI EL DICCIONARIO EXISTE
if (Casting.castingsBD == null) {
    Casting.castingsBD = new HashMap<String, Casting>();
}

// VERIFICAR SI EL CASTING ESTÁ GUARDADO
if (Casting.castingsBD.containsKey(codigoCasting)) {
    String msj = "Existe un casting con este código: " + codigoCasting;
    JOptionPane.showMessageDialog(this, msj);
} else {
    // GUARDAMOS CASTING EN EL DICCIONARIO
    Casting.castingsBD.put(codigoCasting, a);
    // OBTENEMOS EL NÚMERO DE CASTINGS GUARDADOS
    int cuentaCastings = Casting.castingsBD.size();
    String msj = "Este casting fue guardado con éxito. " 
               + "Existen " + cuentaCastings + " castings";
    JOptionPane.showMessageDialog(this, msj);
    limpiarCampos();
}

        
        
        
        
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
     
        int opcion = JOptionPane.showConfirmDialog(this, "¿Desea cerrar?", 
                "OJO - Confirmar", JOptionPane.YES_NO_OPTION, 
                JOptionPane.QUESTION_MESSAGE );
        if (opcion == JOptionPane.YES_OPTION){
        this.dispose();
        }
        
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
      
   // RECUPERAR EL CÓDIGO DEL FORMULARIO
String codigoCasting = campoCodigoCasting.getText();

// Verificamos si el diccionario existe o si está vacío
if (Casting.castingsBD == null || Casting.castingsBD.isEmpty()) {
    String msj = "No existe casting en la BD";
    JOptionPane.showMessageDialog(this, msj);
} 
    
  
else {
    // Buscar el casting en el diccionario a partir de la identificación
    if (Casting.castingsBD.containsKey(codigoCasting)) {
        this.casting = Casting.castingsBD.get(codigoCasting);
        
        campoCodigoCasting.setText(this.casting.codigoCasting);
        campoFechaContratacion.setDate(this.casting.fechaContratacion);
        campoNombreCasting.setText(this.casting.nombre);
        campoDescripcionCasting.setText(this.casting.descripcion);
        campoCosto.setText(this.casting.costo);
        campoTipoDeCasting.setText(this.casting.tipo);
        campoNumeroDePersonas.setText(this.casting.numeroPersonasRequeridas);

        botonEditar.setEnabled(true);
        botonEliminar.setEnabled(true);
    } else {
        String msj = "El casting con código " + codigoCasting + " no existe";
        JOptionPane.showMessageDialog(this, msj);
    }
}


        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void botonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarActionPerformed
        
        //botonBuscarActionPerformed(evt);
        //validamos que el campo identificacion tenga datos
       /* if(campoCodigoCasting.getText() == null || campoCodigoCasting.getText().isEmpty()){
        String msj = "Para editar primero debe tener un candidato " ;
        JOptionPane.showMessageDialog(this, msj);
        limpiarCampos();
        return;
        }
        
        if(campoCodigoCasting.getText().equals(this.candidato.codigo) != true){
           String msj = "La identificacion no coincide con la identificacion del candidato consultado" ;
        JOptionPane.showMessageDialog(this, msj);
        limpiarCampos(); 
        return;
        }
        */
        // Validamos que el campo identificación tenga datos
if (campoCodigoCasting.getText() == null || campoCodigoCasting.getText().isEmpty()) {
    String msj = "Para editar primero debe tener un casting";
    JOptionPane.showMessageDialog(this, msj);
    limpiarCampos();
    return;
}

if (campoCodigoCasting.getText().equals(this.casting.codigoCasting)!= true) {
    String msj = "La identificación no coincide con la identificación del casting consultado";
    JOptionPane.showMessageDialog(this, msj);
    limpiarCampos();
    return;
}
        
        
        
       /* //obtenemos el usuario desde el diccionario a partir del codigo
        this.candidato = Candidato.candidatosBD.get(campoCodigoCasting.getText());
        //obtenemos los nuevos valores ingresados
        
        String altura = campoTipoDeCasting.getText();
        String codigo = campoCodigoCasting.getText();
       
        String colorPelo = campoNumeroDePersonas.getText();
        
        String fotografia = campoNombreCasting.getText();
        
        Date fechaNacimiento = campoFechaContratacion.getDate();
        String provincia = campoDescripcionCasting.getText();
        String sexo = campoCosto.getText();*/
        
        // Obtenemos el casting desde el diccionario a partir del código
this.casting = Casting.castingsBD.get(campoCodigoCasting.getText());

// Obtenemos los nuevos valores ingresados
String codigoCasting = campoCodigoCasting.getText();
Date fechaContratacion = campoFechaContratacion.getDate();
String nombre = campoNombreCasting.getText();
String descripcion = campoDescripcionCasting.getText();
String costo = campoCosto.getText();
String tipo = campoTipoDeCasting.getText();
String numeroPersonasRequeridas = campoNumeroDePersonas.getText();
        
        
        // Cambiar datos del casting
        
this.casting.codigoCasting = codigoCasting;
this.casting.fechaContratacion = fechaContratacion;
this.casting.nombre = nombre;
this.casting.descripcion = descripcion;
this.casting.costo = costo;
this.casting.tipo = tipo;
this.casting.numeroPersonasRequeridas = numeroPersonasRequeridas;

// Guardamos el casting modificado
Casting.castingsBD.put(this.casting.codigoCasting, this.casting);
String msj = "Casting modificado con éxito";
JOptionPane.showMessageDialog(this, msj);
        
        
        
        
    }//GEN-LAST:event_botonEditarActionPerformed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
         //ayudenmeee :,( haaaaaaaaaaaaa
        // Validamos que el campo identificación tenga datos
if (campoCodigoCasting.getText() == null || campoCodigoCasting.getText().isEmpty()) {
    String msj = "Para editar primero debe tener un casting";
    JOptionPane.showMessageDialog(this, msj);
    limpiarCampos();
    return;
}
           
        // Validar que la identificación en el formulario coincida
if (campoCodigoCasting.getText().equals(this.casting.codigoCasting)!= true) {
    String msj = "El código no coincide con el casting consultado";
    JOptionPane.showMessageDialog(this, msj);
    limpiarCampos();
    return;
}
        
       // Confirmación para eliminar el casting
String msj = "¿Seguro que desea eliminar este casting?";
int respuesta = JOptionPane.showConfirmDialog(this, msj, "Confirmar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
if (respuesta == JOptionPane.YES_OPTION) {
    Casting.castingsBD.remove(this.casting.codigoCasting);
    int total = Casting.castingsBD.size();
    String msj2 = "Casting eliminado con éxito. Total de castings restantes: " + total;
    JOptionPane.showMessageDialog(this, msj2);
    limpiarCampos();
}
        
        
        
        
    }//GEN-LAST:event_botonEliminarActionPerformed

    private void campoNumeroDePersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNumeroDePersonasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNumeroDePersonasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCasting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCasting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCasting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCasting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaCasting dialog = new VentanaCasting(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonEditar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JTextField campoCodigoCasting;
    private javax.swing.JTextField campoCosto;
    private javax.swing.JTextField campoDescripcionCasting;
    private org.jdesktop.swingx.JXDatePicker campoFechaContratacion;
    private javax.swing.JTextField campoNombreCasting;
    private javax.swing.JTextField campoNumeroDePersonas;
    private javax.swing.JTextField campoTipoDeCasting;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
