/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package marianorolong.Ventanas.Cliente;

import marianorolong.Ventanas.Cliente.*;
import java.util.HashMap;
import javax.swing.JOptionPane;
import marianorolong.base.Cliente;

/**
 *
 * @author maria
 */
public class VentanaClientes extends javax.swing.JDialog {
    Cliente cliente;
    /**
     * Creates new form VentanaUsuarios
     */
    public VentanaClientes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        campoCodigoCliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        campoNombreCliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        campoDireccionCliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        campoTelefonoCliente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        campoContactoCliente = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        campoActividadCliente = new javax.swing.JTextField();
        botonGuardar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        botonBuscar = new javax.swing.JButton();
        botonEditar = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("..USER FORM");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("FORMULARIO PARA GESTIONAR CLIENTES");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0), 2), "DatosDelCliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 16), new java.awt.Color(255, 153, 0))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Codigo Cliente:");

        campoCodigoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCodigoClienteActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Nombre:");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Dirección:");

        campoDireccionCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDireccionClienteActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Telefono:");

        campoTelefonoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTelefonoClienteActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Persona Contacto:");

        campoContactoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoContactoClienteActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Tipo de Actividad:");

        campoActividadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoActividadClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(campoContactoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(campoCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(campoNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(campoDireccionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(campoTelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(campoActividadCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campoCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(campoNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(campoDireccionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(campoTelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(campoContactoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(campoActividadCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        botonGuardar.setBackground(new java.awt.Color(255, 153, 0));
        botonGuardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonGuardar.setForeground(new java.awt.Color(0, 0, 0));
        botonGuardar.setText("GUARDAR");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        botonCancelar.setBackground(new java.awt.Color(255, 153, 0));
        botonCancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonCancelar.setForeground(new java.awt.Color(0, 0, 0));
        botonCancelar.setText("CANCELAR");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marianorolong/Ventanas/iconos/iconoClientes.png"))); // NOI18N

        botonBuscar.setBackground(new java.awt.Color(255, 153, 0));
        botonBuscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonBuscar.setForeground(new java.awt.Color(0, 0, 0));
        botonBuscar.setText("BUSCAR");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        botonEditar.setBackground(new java.awt.Color(255, 153, 0));
        botonEditar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonEditar.setForeground(new java.awt.Color(0, 0, 0));
        botonEditar.setText("EDITAR");
        botonEditar.setEnabled(false);
        botonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarActionPerformed(evt);
            }
        });

        botonEliminar.setBackground(new java.awt.Color(255, 153, 0));
        botonEliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonEliminar.setForeground(new java.awt.Color(0, 0, 0));
        botonEliminar.setText("ELIMINAR");
        botonEliminar.setEnabled(false);
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(72, 72, 72)
                                        .addComponent(botonEditar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(botonEliminar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(botonCancelar)
                                        .addGap(18, 18, 18)
                                        .addComponent(botonBuscar)
                                        .addGap(18, 18, 18)
                                        .addComponent(botonGuardar)))))))
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonCancelar)
                            .addComponent(botonBuscar)
                            .addComponent(botonGuardar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonEditar)
                            .addComponent(botonEliminar))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoDireccionClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDireccionClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDireccionClienteActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed

        //recuperar los datos ingresados en los campos del formulario
        String codigoCliente = campoCodigoCliente.getText();
        String nombre = campoNombreCliente.getText();
        String direccion = campoDireccionCliente.getText();
        String telefono = campoTelefonoCliente.getText();
        String personaContacto = campoContactoCliente.getText();
        String tipoDeActividad = campoActividadCliente.getText();
        
        //crear variable tipo cliente
        Cliente cl = new Cliente();
        cl.codigoCliente = codigoCliente;
        cl.nombre = nombre;
        cl.direccion = direccion;
        cl.telefono = telefono;
        cl.personaContacto = personaContacto;
        cl.tipoDeActividad = tipoDeActividad;
       // Verificar si el diccionario de clientes existe
if (Cliente.clientesBD == null) {
    Cliente.clientesBD = new HashMap<String, Cliente>();
}

// Verificar si el cliente está guardado
if (Cliente.clientesBD.containsKey(codigoCliente)) {
    String msj = "Existe un cliente con esta identificación: " + codigoCliente;
    JOptionPane.showMessageDialog(this, msj);
} else {
    // Guardamos el cliente en el diccionario
    Cliente.clientesBD.put(codigoCliente, cl);
    // Obtenemos el número de clientes guardados
    int cuentaClientes = Cliente.clientesBD.size();
    String msj = "Este cliente fue guardado con éxito. Existen " + cuentaClientes + " clientes.";
    JOptionPane.showMessageDialog(this, msj);
    limpiarCampos();
}
        
        
    }//GEN-LAST:event_botonGuardarActionPerformed
       public void limpiarCampos(){
        campoCodigoCliente.setText("");
        campoNombreCliente.setText("");
        campoDireccionCliente.setText("");
        campoTelefonoCliente.setText(""); 
        campoContactoCliente.setText("");
        campoActividadCliente.setText("");
        
        botonEditar.setEnabled(false);
        botonEliminar.setEnabled(false);
       }
    
    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed

        int opcion = JOptionPane.showConfirmDialog(this, "¿Desea cerrar?", 
                "OJO - Confirmar", JOptionPane.YES_NO_OPTION, 
                JOptionPane.QUESTION_MESSAGE );
        if (opcion == JOptionPane.YES_OPTION){
        this.dispose();
        
        }
        
        
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed

// RECUPERAR EL CÓDIGO DEL CLIENTE DEL FORMULARIO
String codigoCliente = campoCodigoCliente.getText();

// Verificamos si el diccionario de clientes existe o si está vacío
if (Cliente.clientesBD == null || Cliente.clientesBD.isEmpty()) {
    String msj = "No existen clientes en la BD";
    JOptionPane.showMessageDialog(this, msj);
}
    
    else {
    // Buscar el cliente en el diccionario a partir del código del cliente
    if (Cliente.clientesBD.containsKey(codigoCliente)) {
        this.cliente = Cliente.clientesBD.get(codigoCliente);
        campoCodigoCliente.setText(this.cliente.codigoCliente);
        campoNombreCliente.setText(this.cliente.nombre);
        campoDireccionCliente.setText(this.cliente.direccion);
        campoTelefonoCliente.setText(this.cliente.telefono);
        campoContactoCliente.setText(this.cliente.personaContacto);
        campoActividadCliente.setText(this.cliente.tipoDeActividad);
        botonEditar.setEnabled(true);
        botonEliminar.setEnabled(true);
    } 
    else {
        String msj = "El cliente con código " + codigoCliente + " no existe";
        JOptionPane.showMessageDialog(this, msj);
    }
}

        // TODO add your handling code here:
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void botonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarActionPerformed
       
      
        
        // botonBuscarActionPerformed(evt);
// Validamos que el campo codigoCliente tenga datos
if (campoCodigoCliente.getText() == null || campoCodigoCliente.getText().isEmpty()) {
    String msj = "Para editar primero debe tener un cliente";
    JOptionPane.showMessageDialog(this, msj);
    limpiarCampos();
    return;
}

if(campoContactoCliente.getText().equals(this.cliente.codigoCliente) != true) {
    String msj = "El código del cliente no coincide con el cliente consultado";
    JOptionPane.showMessageDialog(this, msj);
    limpiarCampos();
    return;
}
        
        
        // Obtenemos el cliente desde el diccionario a partir del código del cliente
this.cliente = Cliente.clientesBD.get(campoCodigoCliente.getText());
// Obtenemos los nuevos valores ingresados
String codigoCliente = campoCodigoCliente.getText();
String nombre = campoNombreCliente.getText();
String direccion = campoDireccionCliente.getText();
String telefono = campoTelefonoCliente.getText();
String personaContacto = campoContactoCliente.getText();
String tipoDeActividad = campoActividadCliente.getText();
        
        // Cambiar datos del cliente
this.cliente.codigoCliente = codigoCliente;
this.cliente.nombre = nombre;
this.cliente.direccion = direccion;
this.cliente.telefono = telefono;
this.cliente.personaContacto = personaContacto;
this.cliente.tipoDeActividad = tipoDeActividad;
        
// Guardamos el cliente modificado
Cliente.clientesBD.put(this.cliente.codigoCliente, this.cliente);
String msj = "Cliente modificado con éxito";
JOptionPane.showMessageDialog(this, msj);

      
    }//GEN-LAST:event_botonEditarActionPerformed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        
        // Validamos que el campo codigoCliente tenga datos
        if (campoCodigoCliente.getText() == null || campoCodigoCliente.getText().isEmpty()) {
     String msj = "Para editar primero debe tener un cliente";
     JOptionPane.showMessageDialog(this, msj);
     limpiarCampos();
     return;
    }
        // Validar que el codigoCliente en el formulario coincida
        if(campoCodigoCliente.getText().equals(this.cliente.codigoCliente) != true){
          String msj = "El código del cliente no coincide con el cliente consultado";
    JOptionPane.showMessageDialog(this, msj);
    limpiarCampos();
    return;
    }
       // Confirmar eliminación del cliente
    String msj = "¿Seguro que desea eliminar este cliente?";
    int respuesta = JOptionPane.showConfirmDialog(this, msj, "Confirmar", 
        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
    if (respuesta == JOptionPane.YES_OPTION) {
    Cliente.clientesBD.remove(this.cliente.codigoCliente);
    int total = Cliente.clientesBD.size();
    String msj2 = "Cliente eliminado con éxito. Total de clientes restantes: " + total;
    JOptionPane.showMessageDialog(this, msj2);
    limpiarCampos();
    }
        
        
    }//GEN-LAST:event_botonEliminarActionPerformed

    private void campoTelefonoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTelefonoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTelefonoClienteActionPerformed

    private void campoCodigoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCodigoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCodigoClienteActionPerformed

    private void campoContactoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoContactoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoContactoClienteActionPerformed

    private void campoActividadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoActividadClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoActividadClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaClientes dialog = new VentanaClientes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonEditar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JTextField campoActividadCliente;
    private javax.swing.JTextField campoCodigoCliente;
    private javax.swing.JTextField campoContactoCliente;
    private javax.swing.JTextField campoDireccionCliente;
    private javax.swing.JTextField campoNombreCliente;
    private javax.swing.JTextField campoTelefonoCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
